name: Build Executable
on:
  workflow_dispatch:
    inputs:
      tag:
        description: Release git tag
        type: string
        required: true
  push:

jobs:
  build:
    runs-on: macos-13
    permissions:
      contents: write
      packages: write
      pull-requests: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18.19.0'
      - name: Install Bun
        uses: oven-sh/setup-bun@v2
      - name: Build and Install
        run: |
          npm install @kmamal/sdl
          npm install canvas
          bun i
          bun run build_app
      - name: Compress executable
        run: |
          chmod +x ./gz99
          cp build/amdhelper .
          tar c ./amdhelper | ./gz99 amdhelper.gz
          tar c ./build_app | ./gz99 amdhelper_app.gz
      - name: Publish release
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            ./amdhelper.gz
            ./amdhelper_app.gz
          tag: ${{ inputs.tag }}
          name: AMDHelper ${{ inputs.tag }}
          allowUpdates: true
          artifactErrorsFailBuild: false
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
